services:
  postgres:
    build: ./postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=admin --dbname=vectordb"]
      interval: 10s
      timeout: 5s
      retries: 5

  langfuse:
    image: "langfuse/langfuse:2"
    ports:
      - "3000:3000"
    env_file:
      - ./langfuse/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  chainlit:
    build: ./chainlit
    ports:
      - "8000:8000"
    env_file:
      - ./chainlit/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    develop:
      watch:
        - action: sync
          path: ./chainlit
          target: /chainlit