services:
  postgres:
      build: ./postgres
      ports:
        - "5433:5432"
      volumes:
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./postgres/data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: vectordb
  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    develop:
      watch:
        - action: sync
          path: .
          target: /streamlit